# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-04-07 05:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('reason', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Expense_Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owes', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Expense_Total',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Group_Friend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Profile_Friend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_friend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='splitter.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Settle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Settle_expense', to='splitter.Expense')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Settle_group', to='splitter.Group')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Expense_receiver', to='splitter.Group_Friend')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Expense_sender', to='splitter.Group_Friend')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_friends',
            field=models.ManyToManyField(related_name='Profile_Friends', through='splitter.Profile_Friend', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='group_friend',
            name='friend',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='splitter.Profile_Friend'),
        ),
        migrations.AddField(
            model_name='group_friend',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='splitter.Group'),
        ),
        migrations.AddField(
            model_name='group',
            name='group_friends',
            field=models.ManyToManyField(related_name='Group_Friends', through='splitter.Group_Friend', to='splitter.Profile_Friend'),
        ),
        migrations.AddField(
            model_name='expense_total',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Expense_total_receiver', to='splitter.Group_Friend'),
        ),
        migrations.AddField(
            model_name='expense_total',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Expense_total_sender', to='splitter.Group_Friend'),
        ),
        migrations.AddField(
            model_name='expense_member',
            name='e_splitter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='splitter.Group_Friend'),
        ),
        migrations.AddField(
            model_name='expense_member',
            name='expense',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='splitter.Expense'),
        ),
        migrations.AddField(
            model_name='expense',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='splitter.Group'),
        ),
        migrations.AddField(
            model_name='expense',
            name='payer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='splitter.Group_Friend'),
        ),
        migrations.AlterUniqueTogether(
            name='profile_friend',
            unique_together=set([('profile', 'p_friend')]),
        ),
        migrations.AlterUniqueTogether(
            name='group_friend',
            unique_together=set([('group', 'friend')]),
        ),
        migrations.AlterUniqueTogether(
            name='expense_member',
            unique_together=set([('expense', 'e_splitter')]),
        ),
    ]
