# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-04-07 05:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('splitter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='splitters',
            field=models.ManyToManyField(blank=True, null=True, related_name='splitters_expenses', through='splitter.Expense_Member', to='splitter.Group_Friend'),
        ),
    ]
