# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-03-23 06:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('splitter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='payer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Expense_payer', to='splitter.Group_Friend'),
        ),
        migrations.AlterField(
            model_name='group_friend',
            name='friend',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Profile_Friend_group', to='splitter.Profile_Friend'),
        ),
        migrations.AlterField(
            model_name='settle',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Expense_receiver', to='splitter.Group_Friend'),
        ),
        migrations.AlterField(
            model_name='settle',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Expense_sender', to='splitter.Group_Friend'),
        ),
    ]
