# Generated by Django 4.0.2 on 2022-03-08 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('splitter', '0002_expense_expense_total_friend_group_settle_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='friends',
            new_name='group_friends',
        ),
    ]
