# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-04-07 06:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('splitter', '0003_auto_20220407_0627'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='splitters',
            field=models.ManyToManyField(related_name='Expense_splitters', through='splitter.Expense_Splitter', to='splitter.Group_Friend'),
        ),
    ]
