# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-04-06 12:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('splitter', '0003_auto_20220406_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='splitters',
            field=models.ManyToManyField(related_name='Expense_splitters', to='splitter.Group_Friend'),
        ),
    ]
