# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-04-09 06:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('splitter', '0004_expense_splitters'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense_splitter',
            name='settle',
            field=models.BooleanField(default=False),
        ),
    ]
