# Generated by Django 4.0.2 on 2022-03-09 07:12

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('splitter', '0004_rename_group_friends_group_friends'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Friend',
            new_name='Group_Friend',
        ),
        migrations.RenameField(
            model_name='group',
            old_name='friends',
            new_name='group_friends',
        ),
    ]
