# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-04-06 12:51
from __future__ import unicode_literals

from django.db import migrations


import datetime

from django.db import migrations


def create_through_relations(apps, schema_editor):
    Expense = apps.get_model('splitter', 'Expense')
    Expense_Splitter = apps.get_model('splitter', 'Expense_Splitter')
    for expense in Expense.objects.all():
        for splitter in expense.splitters.all():
            Expense_Splitter(
                expense=expense,
                e_splitter= splitter,
                owes=0
            ).save()


class Migration(migrations.Migration):

    dependencies = [
        ('splitter', '0004_auto_20220406_1248'),
    ]

    operations = [
        migrations.RunPython(create_through_relations, reverse_code=migrations.RunPython.noop),
    ]
