# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-04-09 08:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('splitter', '0005_expense_splitter_settle'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='settled_by',
            field=models.ManyToManyField(related_name='Expense_settled_splitters', to='splitter.Group_Friend'),
        ),
    ]
