# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-04-06 13:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('splitter', '0005_auto_20220406_1251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='splitters',
        ),
    ]
