# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-04-09 08:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('splitter', '0006_expense_settled_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='settled_by',
            field=models.ManyToManyField(blank=True, related_name='Expense_settled_splitters', to='splitter.Group_Friend'),
        ),
    ]
