# Generated by Django 4.0.2 on 2022-03-09 14:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('splitter', '0007_alter_expense_splitters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='splitters',
            field=models.ManyToManyField(related_name='group_friends', to=settings.AUTH_USER_MODEL),
        ),
    ]
