# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-04-09 12:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('splitter', '0009_auto_20220409_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense_splitter',
            name='e_splitter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Expense_Group_Friend', to='splitter.Group_Friend'),
        ),
        migrations.AlterField(
            model_name='expense_splitter',
            name='expense',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Expense_name', to='splitter.Expense'),
        ),
        migrations.AlterField(
            model_name='expense_splitter',
            name='owes',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
