# Generated by Django 4.0.2 on 2022-03-10 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('splitter', '0010_alter_expense_splitters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='splitters',
            field=models.ManyToManyField(related_name='group_friends', to='splitter.Group_Friend'),
        ),
    ]
