# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-04-10 10:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('splitter', '0014_auto_20220410_0431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense_splitter',
            name='owes',
            field=models.IntegerField(null=True),
        ),
    ]
