# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-04-10 12:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('splitter', '0017_auto_20220410_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense_splitter',
            name='owes',
            field=models.IntegerField(),
        ),
    ]
