# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-04-14 06:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('splitter', '0020_auto_20220414_0546'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile_friend',
            old_name='user_friend',
            new_name='user',
        ),
        migrations.AlterUniqueTogether(
            name='profile_friend',
            unique_together=set([('profile', 'user')]),
        ),
    ]
