# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-04-14 13:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('splitter', '0021_auto_20220414_0633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='splitters',
            field=models.ManyToManyField(blank=True, related_name='Expense_splitters', through='splitter.Expense_Splitter', to='splitter.Group_Friend'),
        ),
    ]
